### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by samcarecho** [googlearchive/polymon-issues#5]
Will the Polymon source code be released one day?

**Comment by cdata** [comment]
Yes! We are currently under NDA because some of the back end code uses unannounced features in a Google product. I am hopeful that the game will be open sourced in November, or January at the latest.

**Comment by samcarecho** [comment]
Cool!  :)

**Comment by dwberry** [comment]
@cdata Any update on opening the source?

Particularly interested in how you went from meat-scope to ingesting QR codes...
